name: Lint

on:
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.0

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build workspace packages
        run: bun run build

      - name: Run package checking
        run: bun run lint:packages

      - name: Run type checking
        run: bun run verify-types

      - name: Run linting
        run: bun run lint
